### ISSUE TITLE
Look into organizations we can partner with

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/climate-project#27]
### Overview
Find out what funders are in the space of climate investing and what kinds of projects they invest in. More specifically, how this is relevant to our mission of propelling open-source climate software/hardware 

Impact investors also invest in non-profits. 

### Action Items
- [ ] create list of what type of partnerships we're looking for
> - [ ] Identify criteria of each partner for funding 
> - [ ] conduct informational interviews with potential partners to identify what type of candidate they want
- [ ] finding top organizations for potential partnerships
- [ ] putting these into comparative analysis

### Resources/Instructions
[Competitve Analysis sheet](https://docs.google.com/spreadsheets/d/1ePxxsLpdC4MMvJICyMYljHawhs1j-hpFHZFOtB0fdDc/)

[Organization that gets capital to climate change](https://www.climate-kic.org/countries/united-states/)

[Creo Syndicate - Vet investments for family funds](https://creosyndicate.org/)

[Partner Identification sheet](https://docs.google.com/spreadsheets/d/1LNf3FibvnHAu_L8OzRj0GQoGKZ8ydQfM7KlqxN5Fh2E/edit?usp=sharing)

**Comment by sayalikotkar** [comment]
Progress: Identified categories of organizations we can partner with
Blockers: Needs more research to identify specific organizations
Availability: 3 hours

**Comment by sayalikotkar** [comment]
Link to the high-level planning sheet-

https://drive.google.com/file/d/1jvGqrFQeZzTBN5RHiRaMIMyQiyrqK8xs/view?usp=sharing

**Comment by angle-zhang** [comment]
Helping out with partner identification. Will provide details of potential partners here: https://docs.google.com/spreadsheets/d/1LNf3FibvnHAu_L8OzRj0GQoGKZ8ydQfM7KlqxN5Fh2E/edit?usp=sharing

Sayali can further distill this list and add to the one-sheet

**Comment by angle-zhang** [comment]
Progress: Identified potential partners 
Blockers: need feedback on more specific evaluation metrics for partners
Availability: 4 hours

**Comment by angle-zhang** [comment]
Sayali's feedback: evaluation based on metrics
1. Value Alignment
2. Reach/Reputation (the size of the org and thus their reach)
3. Synergies (their resources and expertise that we could use, and the benefit of our initiative for them)
4. Approachability (how open they are to partnerships, how easy it will be to reach out to them and set up partnerships, do we have mutual connections that we can leverage)

**Comment by angle-zhang** [comment]
meet with @evonhung @jlee2121 about populating interview script 
- fields for partner id doc
- fields in interview doc

**Comment by sayalikotkar** [comment]
Issue replaced by Issue #40
