### ISSUE TITLE
Initial Research Work

### ISSUE THREAD

**Issue by evonhung** [hackforla/climate-project#32]
### Overview
This issue documents all the research work for laying the foundation of identifying user(s) needs, the problem space, and best practices/approaches to creating the ClimateMatch event.

### Action Items @evonhung 
- [ ] Conduct competitive analyses
- [ ] conduct informational interviews with potential partners to identify pain points
> - [ ] identify potential people to interview to learn about climate pipeline #27 
> - [ ] come up with interview questions
> - [ ] schedule interviews
> - [ ] conduct interviews
> - [ ] identify pain points and analyze interview results 

### Resources/Instructions
Google Drive Link to come.

**Comment by angle-zhang** [comment]
progress: informational interview questions draft - https://docs.google.com/document/d/1B-rl7yaCfq1ZNdzlt5XL2pTgSINPdGOkLTGT_jyFur0/edit
blockers: none
availabilty: 4 hours

**Comment by angle-zhang** [comment]
progress: overview of questions + big questions to ask 

todo
- [ ] Section headers for each big questions, arrange other questions under them
- [ ] order in priority 
- [ ] clean up wording

**Comment by sayalikotkar** [comment]
This issue has been replaced by Issues 40, 43 & 27
